version: "3"
services:
  webapp:
    container_name: my-cloudy-webapp
    image: my-cloudy-webapp
    build: ./webapp
    depends_on:
      - "server"

  server:
    container_name: my-cloudy-server
    image: cloudy-server
    build: ./server
    volumes: 
      - ./server/rds-combined-ca-bundle.pem:/app/rds-combined-ca-bundle.pem
    environment:
      - OVERNIGHT_JWT_SECRET=${OVERNIGHT_JWT_SECRET}
      - OVERNIGHT_JWT_EXP=${OVERNIGHT_JWT_EXP}
      - PORT=${PORT}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=db
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DOCDB_USER=${AWS_DOCDB_USER}
      - AWS_DOCDB_PASS=${AWS_DOCDB_PASS}
      - AWS_DOCDB_HOST=${AWS_DOCDB_HOST}
    depends_on:
      - "db"
      
  db:
    build: ./database
    container_name: my-cloudy-db
    image: cloudy-db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432

  proxy:
    container_name: my-cloudy-proxy
    image: cloudy-proxy
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - "webapp"
      - "server"